from typing import Any


BUILTIN_PROVIDERS: list[dict[str, Any]] = [
    {
        "provider_id": "alibaba",
        "display_name": "DashScope",
        "provider_type": "openai",
        "default_protocol": "openai_compatible",
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "embedding_base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1/embeddings",
        "rerank_base_url": "https://dashscope.aliyuncs.com/compatible-api/v1/reranks",
        "api_key_env": "DASHSCOPE_API_KEY",
        "models_endpoint": "https://dashscope.aliyuncs.com/compatible-mode/v1/models",
        "capabilities": ["chat", "embedding", "rerank"],
        "enabled_models": [
            {"id": "qwen-plus", "type": "chat", "source": "manual", "display_name": "qwen-plus"},
            {
                "id": "text-embedding-v4",
                "type": "embedding",
                "source": "manual",
                "display_name": "text-embedding-v4",
                "dimension": 1024,
            },
            {
                "id": "qwen3-rerank",
                "type": "rerank",
                "source": "manual",
                "display_name": "qwen3-rerank",
                "extra": {"rerank_protocol": "dashscope_compatible"},
            },
        ],
    },
    {
        "provider_id": "openai",
        "display_name": "OpenAI",
        "provider_type": "openai",
        "default_protocol": "openai_compatible",
        "base_url": "https://api.openai.com/v1",
        "api_key_env": "OPENAI_API_KEY",
        "models_endpoint": "https://api.openai.com/v1/models",
        "capabilities": ["chat"],
        "enabled_models": [],
    },
    {
        "provider_id": "siliconflow-cn",
        "display_name": "SiliconFlow",
        "provider_type": "openai",
        "default_protocol": "openai_compatible",
        "base_url": "https://api.siliconflow.cn/v1",
        "embedding_base_url": "https://api.siliconflow.cn/v1/embeddings",
        "rerank_base_url": "https://api.siliconflow.cn/v1/rerank",
        "api_key_env": "SILICONFLOW_API_KEY",
        "models_endpoint": "https://api.siliconflow.cn/v1/models?sub_type=chat",
        "embedding_models_endpoint": "https://api.siliconflow.cn/v1/models?sub_type=embedding",
        "rerank_models_endpoint": "https://api.siliconflow.cn/v1/models?sub_type=reranker",
        "capabilities": ["chat", "embedding", "rerank"],
        "enabled_models": [
            {
                "id": "deepseek-ai/DeepSeek-V4-Flash",
                "type": "chat",
                "source": "manual",
                "display_name": "deepseek-ai/DeepSeek-V4-Flash",
            },
            {
                "id": "Pro/BAAI/bge-m3",
                "type": "embedding",
                "source": "manual",
                "display_name": "Pro/BAAI/bge-m3",
                "dimension": 1024,
                "batch_size": 40,
            },
            {
                "id": "Pro/BAAI/bge-reranker-v2-m3",
                "type": "rerank",
                "source": "manual",
                "display_name": "Pro/BAAI/bge-reranker-v2-m3",
            },
        ],
    },
    {
        "provider_id": "deepseek",
        "display_name": "DeepSeek",
        "provider_type": "openai",
        "default_protocol": "openai_compatible",
        "base_url": "https://api.deepseek.com",
        "api_key_env": "DEEPSEEK_API_KEY",
        "models_endpoint": "https://api.deepseek.com/models",
        "capabilities": ["chat"],
        "enabled_models": [],
    },
    {
        "provider_id": "minimax-cn",
        "display_name": "MiniMax",
        "provider_type": "openai",
        "default_protocol": "openai_compatible",
        "base_url": "https://api.minimaxi.com/v1",
        "api_key_env": "MINIMAX_API_KEY",
        "models_endpoint": "https://api.minimaxi.com/v1/models",
        "capabilities": ["chat"],
        "enabled_models": [],
    },
    {
        "provider_id": "xiaomi",
        "display_name": "XiaomiMiMo",
        "provider_type": "openai",
        "default_protocol": "openai_compatible",
        "base_url": "https://api.xiaomimimo.com/v1",
        "api_key_env": "XIAOMI_MIMO_API_KEY",
        "models_endpoint": "https://api.xiaomimimo.com/v1/models",
        "capabilities": ["chat"],
        "enabled_models": [],
    },
    {
        "provider_id": "xiaomi-token-plan-cn",
        "display_name": "XiaomiMiMo Token Plan",
        "provider_type": "openai",
        "default_protocol": "openai_compatible",
        "base_url": "https://token-plan-cn.xiaomimimo.com/v1",
        "api_key_env": "XIAOMI_MIMO_TOKEN_PLAN_API_KEY",
        "models_endpoint": "https://token-plan-cn.xiaomimimo.com/v1/models",
        "capabilities": ["chat"],
        "enabled_models": [],
    },
    {
        "provider_id": "modelscope",
        "display_name": "ModelScope",
        "provider_type": "openai",
        "default_protocol": "openai_compatible",
        "base_url": "https://api-inference.modelscope.cn/v1",
        "api_key_env": "MODELSCOPE_ACCESS_TOKEN",
        "models_endpoint": "https://api-inference.modelscope.cn/v1/models",
        "capabilities": ["chat"],
        "enabled_models": [],
    },
]
